
from modules.log_utils import divider_with_time, log_header_with_time, log_with_time


def print_info():
    log_header_with_time("Info")
    log_with_time("   0. Info")
    log_with_time("Display information about the script and its functionalities.")
    divider_with_time()
    log_with_time("   1. Print menu")
    log_with_time("Display the available menu options.")
    divider_with_time()
    log_with_time("   2. New directory path")
    log_with_time("Input:  'directory path'")
    log_with_time("Change the current directory path.")
    divider_with_time()
    log_with_time("   3. Auto")
    log_with_time("Input:  'files name'")
    log_with_time("From:   'directory path'")
    log_with_time("To:     'directory path'")
    log_with_time("Automatically performs the following actions:")
    log_with_time("Rename, Move, Convert, Compress, and Remove")
    divider_with_time()
    log_with_time("   4. Rename")
    log_with_time("Input:  'files name'")
    log_with_time("From:   'directory path'")
    log_with_time("To:     'directory path'")
    log_with_time("Renames all files in the directory that contain a volume number.")
    log_with_time("Extracts numbers from the name and adds them in the format 'v***'.")
    log_with_time("Example: 'something (something) 1 something' ==> 'files name v001'")
    divider_with_time()
    log_with_time("   5. Move files")
    log_with_time("From:   'directory path'")
    log_with_time("To:     'archives' and 'pdf' subfolders")
    log_with_time("Moves all cbz and cbr files to the 'archives' folder")
    log_with_time("and all pdf files to the 'pdf' folder.")
    divider_with_time()
    log_with_time("   6. Convert files")
    log_with_time("From:   'archives' subfolder")
    log_with_time("To:     'pdf' subfolder")
    log_with_time("Clone and converts all cbz and cbr files to pdf files.")
    divider_with_time()
    log_with_time("   7. Compress files")
    log_with_time("From:   'pdf' subfolder")
    log_with_time("To:     'compressed' subfolder")
    log_with_time("Clone and compress files from the 'pdf' folder into the 'compressed' folder.")
    divider_with_time()
    log_with_time("   8. Remove subfolders")
    log_with_time("From:   'compressed' subfolder")
    log_with_time("To:     'directory path'")
    log_with_time("Moves files from the 'compressed' folder to its parent directory")
    log_with_time("and deletes subfolders: 'archives', 'pdf', 'compressed' ")
    divider_with_time()
    log_with_time("   9. Combine pdf files")
    log_with_time("From:   'directory path'")
    log_with_time("To:     'directory path'")
    log_with_time("Combines all pdf files in the directory into a single pdf file.")
    divider_with_time()
    log_with_time("   10. Combine subfolders images")
    log_with_time("From:   'directory path'")
    log_with_time("To:     'pdf' subfolder")
    log_with_time("Combines all image files in the subfolders into a single pdf file.")
    divider_with_time()

def print_menu():
    log_header_with_time("Choose an action")
    log_with_time("    0. Info")
    log_with_time("    1. Print menu")
    log_with_time("    2. New directory path")
    divider_with_time()
    log_with_time("    3. Auto")
    log_with_time("    4. Rename")
    log_with_time("    5. Move to subfolders")
    log_with_time("    6. Convert")
    log_with_time("    7. Compress")
    log_with_time("    8. Remove subfolders")
    divider_with_time()
    log_with_time("    9. Combine pdf files")
    log_with_time("   10. Combine subfolders images")
    divider_with_time()
